name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  DOTNET_VERSION: "6.0.x"
  NUGET_SOURCE: "https://api.nuget.org/v3/index.json"

jobs:
  runtime:
    runs-on: ubuntu-latest
    env:
      source-directory: ./src/runtime
      source-project: AutomationIoC.Runtime.csproj
      test-directory: ./test/runtime
      test-project: AutomationIoC.Runtime.Test.csproj

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dependencies
        run: |
          dotnet restore ${{ env.source-directory }}/${{ env.source-project }}
          dotnet restore ${{ env.test-directory }}/${{ env.test-project }}

      - name: Build
        working-directory: ${{ env.source-directory }}
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: ${{ env.test-directory }}
        run: dotnet test --no-restore --verbosity normal
  sdk:
    runs-on: ubuntu-latest
    env:
      source-directory: ./src/sdk
      source-project: AutomationIoC.SDK.csproj
      test-directory: ./test/sdk
      test-project: AutomationIoC.SDK.Test.csproj

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dependencies
        run: |
          dotnet restore ${{ env.source-directory }}/${{ env.source-project }}
          dotnet restore ${{ env.test-directory }}/${{ env.test-project }}

      - name: Build
        working-directory: ${{ env.source-directory }}
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: ${{ env.test-directory }}
        run: dotnet test --no-restore --verbosity normal

  tools:
    runs-on: ubuntu-latest
    env:
      source-directory: ./src/tools
      source-project: AutomationIoC.Tools.csproj
      test-directory: ./test/tools
      test-project: AutomationIoC.Tools.Test.csproj

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dependencies
        run: |
          dotnet restore ${{ env.source-directory }}/${{ env.source-project }}
          dotnet restore ${{ env.test-directory }}/${{ env.test-project }}

      - name: Build
        working-directory: ${{ env.source-directory }}
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: ${{ env.test-directory }}
        run: dotnet test --no-restore --verbosity normal

  release:
    needs: [runtime, sdk, tools]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    env:
      project: ./automation/AutomationIoC.csproj
      release-path: ./automation/bin/Release

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dependencies
        working-directory: ./src
        run: dotnet restore ${{ env.project }}

      - name: Create Release Packages
        working-directory: ./src
        run: dotnet pack ${{ env.project }} -c Release --no-restore -p:PackageVersion=${{ github.event.release.tag_name }}

      - name: Push Release Packages
        working-directory: ./src
        run: dotnet nuget push ${{ env.release-path }}/AutomationIoC.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.NUGET_SOURCE }}
